<a href="https://colab.research.google.com/github/seokmin1/PDM08/blob/main/numpy/numpy_3_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## random 서브모듈
> [데이터싸이언스 스쿨:난수발생](https://datascienceschool.net/01%20python/03.05%20%EB%82%9C%EC%88%98%20%EB%B0%9C%EC%83%9D%EA%B3%BC%20%EC%B9%B4%EC%9A%B4%ED%8C%85.html)

In [1]:
import numpy as np

## 난수 생성
> NumPy의 random 서브모듈은 난수를 생성하는 다양한 명령을 제공.

- rand: 0부터 1사이의 균일 분포 (uniform distribution)
- randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)
- randint: 균일 분포의 정수 난수 (uniform int)

> randn()은 평균 0, 표준편차 1 인 가우시안 정규분포를 생성.

### rand: 0부터 1사이의 균일 분포 (uniform distribution)

In [2]:
np.random.rand(5)

array([0.36482444, 0.18055289, 0.73875435, 0.5158337 , 0.96349973])

In [3]:
np.random.rand(5)

array([0.54397759, 0.11724546, 0.45415975, 0.68273181, 0.60003606])

### randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)

In [4]:
np.random.randn(5)

array([ 0.94484593, -0.81572008,  0.29315773, -0.23624597,  1.85399738])

In [36]:
np.random.randn(5)

array([ 0.11514787, -0.37914756, -1.7423562 , -1.30324275,  0.60512008])

### randint: 균일 분포의 정수 난수 (uniform int)
- numpy.random.randint(low, high=None, size=None, dtype='l')

In [27]:
np.random.randint(5)

2

In [42]:
# die number
np.random.randint(1,7)

3

In [47]:
np.random.randint(5,9) 

8

In [39]:
np.random.randint(0,10,5)

array([9, 3, 7, 0, 2])

In [7]:
np.random.randint(0,10,5)

array([8, 7, 5, 9, 9])

---

## 난수 생성 seed 설정
- numpy.random.seed(seed=None)
- np.random.seed(number)

In [48]:
np.random.seed()

In [51]:
np.random.rand(5)

array([0.51130149, 0.78328212, 0.48616577, 0.28866597, 0.40186571])

In [10]:
np.random.rand(5)

array([0.82913534, 0.51551919, 0.87697189, 0.29718403, 0.82479885])

### 동일한 무작위수 생성
- seed를 고정하고 무작위수 생성

In [52]:
np.random.seed(1234)

In [53]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [13]:
np.random.rand(5)

array([0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [54]:
np.random.seed(1234)

In [55]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

### seed 고정 후에 randint(5)

In [56]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [17]:
np.random.randint(1,10,5)

array([6, 3, 7, 4, 1])

In [57]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [18]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [19]:
# seed 변경
np.random.seed(0)
np.random.randint(1,10,5)

array([6, 1, 4, 4, 8])

---
---

## DIY: 도전 코딩 - numpy 정리 과제
- 생성된 마구잡이수를 조사하고 사용하기 
- 9월19일 자정 마감.

### [도전 1.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수의 빈도를 구하시오. 

In [85]:
# n1000=
from collections import Counter
n1000 = np.random.randint(0,10,1000)
n1000
arr= n1000
frequency = Counter(arr)
print(frequency)


Counter({5: 115, 6: 111, 4: 108, 7: 108, 1: 106, 8: 96, 3: 96, 0: 91, 2: 85, 9: 84})


In [65]:
np.unique(n1000)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 각 수의 빈도

### [도전 2.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수가 처음 출현하는 인덱스를 구하시오.
> 0이 처음 나타날 때의 인덱스, 1이 처음 나타날 때의 인덱스, ... 

In [64]:
n1000[0],n1000[800]

(7, 4)

In [ ]:
# 각 수가 처음 출현하는 인덱스


In [ ]:
# n1000[index]

### [도전 3.] seed를 1234로 고정하고, 위의 도전1,2를 다시 해보시오. 

### [도전 4.] 0부터 999까지의 마구잡이 정수로 구성되는 28X28 이차원배열을 만드시오.
- 시드를 고정 : np.random.seed(1234)
1. 각 행의 최대값, 최소갑을 구하시오.
2. 배열 전체의 최대값, 최소값을 구하시오.
3. 배열전체의 최대값, 최소값의 index를 각각 찾으시오.

---
---

## python graphics
- matplotlib
> import matplotlib.pyplot as plt

### 무작위수 분포 그려보기

In [ ]:
import matplotlib.pyplot as plt

In [86]:
plt.hist(n1000,label=range(0,10), color='red') #
# plt.show()

NameError: ignored

### [도전] 균일분포와 정규분포를 비교하는 그림을 그리시오.

In [87]:
plt.hist(np.random.rand(1000), bins(50))

NameError: ignored

In [ ]:
plt.hist(np.random.randn(1000))

## 보충 코드

In [75]:
n1000 = np.random.randint(0,10,1000)
n1000

array([0, 9, 9, 0, 5, 6, 6, 0, 1, 2, 0, 8, 1, 4, 6, 8, 9, 9, 6, 2, 4, 5,
       2, 9, 7, 0, 9, 4, 0, 9, 5, 4, 9, 8, 2, 7, 2, 4, 5, 1, 4, 1, 0, 2,
       8, 7, 7, 6, 3, 4, 6, 6, 6, 5, 7, 2, 5, 8, 2, 2, 0, 7, 0, 0, 4, 1,
       0, 7, 3, 5, 0, 2, 3, 9, 5, 5, 1, 8, 0, 1, 7, 0, 4, 4, 1, 4, 2, 5,
       8, 0, 0, 9, 3, 4, 4, 5, 1, 8, 2, 5, 0, 5, 4, 9, 7, 4, 1, 5, 9, 5,
       5, 2, 0, 0, 9, 8, 3, 7, 8, 6, 5, 3, 7, 0, 0, 5, 6, 3, 6, 6, 9, 4,
       1, 5, 2, 4, 6, 9, 4, 3, 3, 3, 4, 9, 2, 4, 7, 2, 5, 2, 5, 5, 3, 6,
       8, 9, 2, 3, 1, 4, 9, 9, 0, 1, 7, 0, 5, 0, 3, 1, 5, 3, 0, 5, 0, 1,
       4, 5, 3, 3, 5, 7, 0, 6, 5, 9, 0, 6, 9, 1, 5, 5, 7, 3, 9, 0, 9, 4,
       0, 4, 8, 6, 9, 6, 2, 8, 7, 8, 8, 0, 4, 6, 2, 7, 6, 4, 7, 6, 7, 4,
       2, 8, 3, 1, 9, 8, 4, 5, 1, 1, 5, 3, 3, 5, 0, 9, 3, 6, 1, 6, 1, 1,
       4, 8, 3, 1, 5, 9, 7, 0, 8, 7, 5, 4, 9, 0, 3, 9, 1, 7, 1, 7, 7, 7,
       6, 6, 5, 3, 2, 0, 8, 7, 6, 2, 7, 9, 8, 6, 4, 1, 7, 1, 6, 7, 6, 4,
       3, 7, 4, 8, 9, 6, 3, 8, 1, 0, 8, 7, 2, 6, 6,

In [76]:
value, count= np.unique(n1000, return_counts=True)

In [77]:
value, count

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([101, 103,  97,  90, 108, 104, 105,  82, 106, 104]))